### ISSUE TITLE
Badge links not working

### ISSUE THREAD

**Issue by Davoleo** [way2muchnoise/CurseForgeBadge#12]
I don't know if it's an issue of my computer, but I'll post this in case it's a CF project linking bug

this is from http://cf.way2muchnoise.eu
![image](https://user-images.githubusercontent.com/24458276/49973131-2ccfd380-ff34-11e8-8ee3-6a68f0c3e470.png)

this is from https://github.com/Davoleo/Metallurgy-4-Reforged
![image](https://user-images.githubusercontent.com/24458276/49973148-46711b00-ff34-11e8-91e7-e9a96c8e20ce.png)

**Comment by way2muchnoise** [comment]
Fixed in aa87c4b526f40c7febe3f80b16c4506cb513f0ae it seemed like Curse is throwing 403's at requests made with the python User-Agent header.
