### ISSUE TITLE
Support "For the badge" styling

### ISSUE THREAD

**Issue by TheCodedOne** [way2muchnoise/CurseForgeBadge#14]
Add a badge styling option to make badges support the [forthebadge](https://forthebadge.com) style

**Comment by way2muchnoise** [comment]
To Do:
- [ ] Add toUppercase for text
- [ ] Fix bold padding

Note to self, these could be done both with some apply transformation depending on style. For this style it could be something like uppercasing the text and doing width time 1.2 or so.

**Comment by RedSparr0w** [comment]
Would you consider adding a _[shields.io endpoint badge](https://shields.io/endpoint)_ compatible endpoint?

For example the following json would return this badge:
[![](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise)](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise)
```js
{
  'schemaVersion': 1,
  'label': 'downloads',
  'labelColor': 'E04E14',
  'message': '14,883,554',
  'color': '2D2D2D',
  'cacheSeconds': 86400,
  'style': 'for-the-badge',
  'logoSvg': '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 43 24"><path fill="#131313" d="M11.3 0l.7 3H0s.2.9.3 1c.3.5.6 1.1 1 1.5 1.9 2.2 5.2 3.1 7.9 3.6 1.9.4 3.8.5 5.7.6l2.2 5.9h1.2l.7 1.9h-1L16.3 23H33l-1.7-5.5h-1l.7-1.9h1.2s1-6.1 4.1-8.9c3-2.8 6.7-3.2 6.7-3.2V0H11.3zm16.8 15.1c-.8.5-1.7.5-2.3.9-.4.2-.6.8-.6.8-.4-.9-.9-1.2-1.5-1.4-.6-.2-1.7-.1-3.2-1.4-1-.9-1.1-2.1-1-2.7v-.1-.2c0-.1 0-.2.1-.3.2-.6.7-1.2 1.7-1.6 0 0-.7 1 0 2 .4.6 1.2.9 1.9.5.3-.2.5-.6.6-.9.2-.7.2-1.4-.4-1.9-.9-.8-1.1-1.9-.5-2.6 0 0 .2.9 1.1.8.6 0 .6-.2.4-.4-.1-.3-1.4-2.2.5-3.6 0 0 1.2-.8 2.6-.7-.8.1-1.7.6-2 1.4v.1c-.3.8-.1 1.7.5 2.5.4.6.9 1.1 1.1 1.9-.3-.1-.5 0-.7.2-.2.2-.3.6-.2.9.1.2.3.4.5.4H27c.3-.1.5-.5.4-.8.2.2.3.7.2 1 0 .3-.2.6-.3.8-.1.2-.3.4-.4.6-.1.2-.2.4-.2.6 0 .2 0 .5.1.7.4.6 1.2 0 1.4-.5.3-.6.2-1.3-.2-1.9 0 0 .7.4 1.2 1.8.4 1.2-.3 2.6-1.1 3.1z"/></svg>',
  'logoWidth': '25'
}
```

Which can also still be customized:

no label
[![](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&label=)](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&label=)
different style
[![](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=flat)](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=flat)
[![](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=flat-square)](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=flat-square)
[![](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=social)](https://img.shields.io/badge/endpoint.svg?url=https://shields.redsparr0w.com/2473/way2muchnoise&style=social)

**Comment by way2muchnoise** [comment]
@RedSparr0w Could you create a new issue for that? I didn't know shields.io had an endpoint service :o
