### ISSUE TITLE
Available for: Error

### ISSUE THREAD

**Issue by sargunv** [way2muchnoise/CurseForgeBadge#17]
The `/versions/` badge for my new mod shows an error instead of the versions: 

```
![](http://cf.way2muchnoise.eu/versions/always-drop-loot.svg)
```

![](http://cf.way2muchnoise.eu/versions/always-drop-loot.svg)

The downloads badge works just fine for the same mod: 

```
![](http://cf.way2muchnoise.eu/always-drop-loot.svg)
```

![](http://cf.way2muchnoise.eu/always-drop-loot.svg)

**Comment by sargunv** [comment]
Looks like the error stopped happening when I started supporting 1.13. It happened when 1.12 was the only supported version. I assume it fails when only a single version is in the list.

**Comment by Lykrast** [comment]
I confirm the same happens to all my mods, which are also only for 1.12.2.

```
![](http://cf.way2muchnoise.eu/versions/defiled-lands.svg)
![](http://cf.way2muchnoise.eu/versions/prodigy-tech.svg)
![](http://cf.way2muchnoise.eu/versions/mystical-wildlife.svg)
![](http://cf.way2muchnoise.eu/versions/harvesters-night.svg)
![](http://cf.way2muchnoise.eu/versions/jetif.svg)
![](http://cf.way2muchnoise.eu/versions/universalbestiary.svg)
![](http://cf.way2muchnoise.eu/versions/glassential.svg)
```

![](http://cf.way2muchnoise.eu/versions/defiled-lands.svg)
![](http://cf.way2muchnoise.eu/versions/prodigy-tech.svg)
![](http://cf.way2muchnoise.eu/versions/mystical-wildlife.svg)
![](http://cf.way2muchnoise.eu/versions/harvesters-night.svg)
![](http://cf.way2muchnoise.eu/versions/jetif.svg)
![](http://cf.way2muchnoise.eu/versions/universalbestiary.svg)
![](http://cf.way2muchnoise.eu/versions/glassential.svg)
