### ISSUE TITLE
Everything returns "Error"

### ISSUE THREAD

**Issue by magneticflux-** [way2muchnoise/CurseForgeBadge#20]
It looks like CurseForge changed some things, and now the parsing is failing.

**Comment by magneticflux-** [comment]
It's probably only the regexes that need to be changed, but I think moving to the actual API would be the best course overall. I don't have any experience with Python/Flask, but I do know how to whip up a Spring Boot server that queries the API with Retrofit and caches responses.

**Comment by RedSparr0w** [comment]
I'm fairly sure the curse api doesn't provide a lot of the information that is needed, unless it has been updated recently.

**Comment by magneticflux-** [comment]
@RedSparr0w You're right, it doesn't! I'm developing with [this](https://www.cfwidget.com/) instead, and it's going well so far.

**Comment by way2muchnoise** [comment]
Fixed with cf8ab783ab190cc9524a7ad7375104262529c5f7 was broken due to CF web page redesign

**Comment by RedSparr0w** [comment]
@magneticflux- 
Thanks that's cool, didn't know about that API!

[![badge](https://img.shields.io/badge/dynamic/json.svg?style=for-the-badge&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)](https://img.shields.io/badge/dynamic/json.svg?style=for-the-badge&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)

[![badge](https://img.shields.io/badge/dynamic/json.svg?style=flat&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)](https://img.shields.io/badge/dynamic/json.svg?style=flat&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)

[![badge](https://img.shields.io/badge/dynamic/json.svg?style=flat-square&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)](https://img.shields.io/badge/dynamic/json.svg?style=flat-square&label=FTB%20Infinity%20Evolved&query=%24.download.version&url=https%3A%2F%2Fapi.cfwidget.com%2Fmodpacks%2Fminecraft%2F227724-ftb-infinity-evolved&prefix=v&colorB=2D2D2D&colorA=E04E14&logoWidth=30&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MyAyNCI+PHBhdGggZmlsbD0iIzEzMTMxMyIgZD0iTTExLjMgMGwuNyAzSDBzLjIuOS4zIDFjLjMuNS42IDEuMSAxIDEuNSAxLjkgMi4yIDUuMiAzLjEgNy45IDMuNiAxLjkuNCAzLjguNSA1LjcuNmwyLjIgNS45aDEuMmwuNyAxLjloLTFMMTYuMyAyM0gzM2wtMS43LTUuNWgtMWwuNy0xLjloMS4yczEtNi4xIDQuMS04LjljMy0yLjggNi43LTMuMiA2LjctMy4yVjBIMTEuM3ptMTYuOCAxNS4xYy0uOC41LTEuNy41LTIuMy45LS40LjItLjYuOC0uNi44LS40LS45LS45LTEuMi0xLjUtMS40LS42LS4yLTEuNy0uMS0zLjItMS40LTEtLjktMS4xLTIuMS0xLTIuN3YtLjEtLjJjMC0uMSAwLS4yLjEtLjMuMi0uNi43LTEuMiAxLjctMS42IDAgMC0uNyAxIDAgMiAuNC42IDEuMi45IDEuOS41LjMtLjIuNS0uNi42LS45LjItLjcuMi0xLjQtLjQtMS45LS45LS44LTEuMS0xLjktLjUtMi42IDAgMCAuMi45IDEuMS44LjYgMCAuNi0uMi40LS40LS4xLS4zLTEuNC0yLjIuNS0zLjYgMCAwIDEuMi0uOCAyLjYtLjctLjguMS0xLjcuNi0yIDEuNHYuMWMtLjMuOC0uMSAxLjcuNSAyLjUuNC42LjkgMS4xIDEuMSAxLjktLjMtLjEtLjUgMC0uNy4yLS4yLjItLjMuNi0uMi45LjEuMi4zLjQuNS40SDI3Yy4zLS4xLjUtLjUuNC0uOC4yLjIuMy43LjIgMSAwIC4zLS4yLjYtLjMuOC0uMS4yLS4zLjQtLjQuNi0uMS4yLS4yLjQtLjIuNiAwIC4yIDAgLjUuMS43LjQuNiAxLjIgMCAxLjQtLjUuMy0uNi4yLTEuMy0uMi0xLjkgMCAwIC43LjQgMS4yIDEuOC40IDEuMi0uMyAyLjYtMS4xIDMuMXoiLz48L3N2Zz4=)
