### ISSUE TITLE
Badge does not work for new mods

### ISSUE THREAD

**Issue by Alpvax** [way2muchnoise/CurseForgeBadge#21]
Line in get_project uses the old url scheme: https://github.com/way2muchnoise/CurseForgeBadge/blob/a6e85baa2f2786ef7406f1319cc33be6550e232d/CFReader.py#L10

However new mods do not have that link redirected. For example my mod [GoProne](https://www.curseforge.com/minecraft/mc-mods/goprone) does not work with the badge as the `/projects/` link ([here](https://minecraft.curseforge.com/projects/goprone)) returns a `404` with no redirect.

**Comment by way2muchnoise** [comment]
Yeah, I was kinda expecting this. Will have to have a think on how to fix.

**Comment by Alpvax** [comment]
You could default to the mc-mods link, with a fallback to modpacks if that link does not resolve.
Alternatively, you could add support for `/mod/project.svg` and similar. Although that is very similar to /mods/
