### ISSUE TITLE
Wide badges can have sizing issues

### ISSUE THREAD

**Issue by itsmeow** [way2muchnoise/CurseForgeBadge#22]
For example, this badge is really wide, and it has less height than other badges
![image](https://user-images.githubusercontent.com/10366817/62417296-281e7380-b61a-11e9-9ce8-541987ed3f6a.png)
Seen here https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus

**Comment by way2muchnoise** [comment]
Issue is with CF description page, not caused by CFBadge
