### ISSUE TITLE
Badge displayed correctly when visiting URL but not in README.md

### ISSUE THREAD

**Issue by realmayus** [way2muchnoise/CurseForgeBadge#24]
I am using the following text to show the badge in my readme:
`[![Download on CF](https://cf.way2muchnoise.eu/title/361476_Get_on%20CF.svg?badge_style=for_the_badge)](https://www.curseforge.com/minecraft/mc-mods/youmatter)`
When I visit the URL `https://cf.way2muchnoise.eu/title/361476_Get_on%20CF.svg?badge_style=for_the_badge` in my browser, everything works but the badge shows the Alt text when used in the readme.

**Comment by starlingfire** [comment]
Try using http instead of https.

[As per right on the homepage:](http://cf.way2muchnoise.eu/)

> The base url is https://cf.way2muchnoise.eu. This url can be appended by following patterns. **Use of https is available, but GitHub doesn't seem to like that.** The examples below are but a subset of all possibilities go check out the code on Github for all possible options

**Comment by realmayus** [comment]
Thanks, that fixed the issue.
