### ISSUE TITLE
Feature Request - Update Colour / Logo

### ISSUE THREAD

**Issue by SnowShock35** [way2muchnoise/CurseForgeBadge#25]
Would it be possible to add support or change the colour scheme to match the current CF (Twitch) colours? :-)

**Comment by way2muchnoise** [comment]
Colour can already be changed, just not documented
https://github.com/way2muchnoise/CurseForgeBadge/blob/master/CurseForgeBadge.py#L22

**Comment by SnowShock35** [comment]
> Colour can already be changed, just not documented
> https://github.com/way2muchnoise/CurseForgeBadge/blob/master/CurseForgeBadge.py#L22

Are they passed as query strings or some other format? Not familiar with Flask.

**Comment by way2muchnoise** [comment]
That format, the parts between <> are the "parameters". Should have used get params, but it seems like that completely passed by me while writing this.

**Comment by SnowShock35** [comment]
So like this then?

`https://cf.way2muchnoise.eu/full_000000_downloads.svg?badge_style=for_the_badge&l_color=6441a4`

**Comment by SnowShock35** [comment]
Figured it out now. Didn't realise the brackets were literal characters that go in the URL. Thanks for the help 😃
