### ISSUE TITLE
Flat and square styles are swapped

### ISSUE THREAD

**Issue by Kneelawk** [way2muchnoise/CurseForgeBadge#28]
Currently requesting `http://cf.way2muchnoise.eu/heart-of-the-machine.svg?badge_style=flat`
displays this badge: ![Heart of the Machine](http://cf.way2muchnoise.eu/heart-of-the-machine.svg?badge_style=flat)
while requesting `http://cf.way2muchnoise.eu/heart-of-the-machine.svg?badge_style=square`
displays this badge: ![Heart of the Machine](http://cf.way2muchnoise.eu/heart-of-the-machine.svg?badge_style=square)

**Comment by Kneelawk** [comment]
This might be due to confusion in comparison to [shields.io](https://shields.io)'s api where `flat_square` produces a badge with no gradient and square edges, while `flat` only produces a badge without a gradient. Where it appears that here, you don't have a badge with a gradient, the badge without the gradient is default, and the `flat` style yeilds a badge with square edges.

**Comment by Kneelawk** [comment]
If this api difference is intentional, feel free to close this issue.

**Comment by way2muchnoise** [comment]
There is only two badge styles for_the_badge and flat.
Square is not a valid style. (so yes, different by design, although not intended)

I plan on implementing an endpoint to support shields.io, see #15
