### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dbarnes181** [way2muchnoise/CurseForgeBadge#31]
Just a suggestion, but documentation would be very useful.

I don't understand how to use this from README.md or from https://cf.way2muchnoise.eu/

**Comment by way2muchnoise** [comment]
Yeah, just never got around to it. Looking for something in particular?

**Comment by dbarnes18** [comment]
No, I did manage to figure it out!
If you want, I can create some docs for you.

**Comment by way2muchnoise** [comment]
Feel free to create a PR with some documentation or create some pages on the github wiki
