### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by MelanX** [way2muchnoise/CurseForgeBadge#34]
The page you are looking for is temporarily unavailable. Please try again later.

I don't know if you already know about it but it's down atm. Didn't know where I could contact you :)

**Comment by DAmNRelentless** [comment]
I also recognized the badges have been down.
I doubt he is very active any longer, would be cool if they come back though!

**Comment by way2muchnoise** [comment]
Thx for letting me know, service has been restarted and badges are back!
