### ISSUE TITLE
Website is down - badges unavailable

### ISSUE THREAD

**Issue by DenisD3D** [way2muchnoise/CurseForgeBadge#39]
Proboably the same as #38
Website is currently down with the following error
![image](https://user-images.githubusercontent.com/35769613/163232700-75500b2f-76d5-4fc8-a219-ee12cdd0993d.png)

**Comment by way2muchnoise** [comment]
Brought it back up, really need to investigate some type of auto restarting script when this happens...

**Comment by MrTroble** [comment]
The issue reappeared so did open a new one #41

**Comment by way2muchnoise** [comment]
Back up and running
