### ISSUE TITLE
The page seems to be unavailable currently

### ISSUE THREAD

**Issue by MrTroble** [way2muchnoise/CurseForgeBadge#41]
https://cf.way2muchnoise.eu/title/gir-signal-mod.svg?badge_style=for_the_badge

![Screenshot 2022-04-18 at 17-05-51 The page is temporarily unavailable](https://user-images.githubusercontent.com/13779831/163828508-c4cf25f0-6ef5-4a58-a17a-e0170df1d381.png)

The side seems to have an issue currently.
I could not find a better way to notify you of this outage, therefore I opened this issue.

Thank you for your time and your work,
Cheers
~MrTroble

**Comment by MrTroble** [comment]
Reappearance of #39 and #40

**Comment by way2muchnoise** [comment]
Back up and running
