### ISSUE TITLE
Website / Service down?

### ISSUE THREAD

**Issue by ApexModder** [way2muchnoise/CurseForgeBadge#42]
The website and service that runs the badges behind the scenes seem to be down, no badges that make use of this load and show broken/failed to load images instead.

Navigating to https://cf.way2muchnoise.eu/ leads to the browser timing out

![image](https://user-images.githubusercontent.com/29412632/193081276-ab9bacab-fa13-4e83-97f7-9167f3b448a4.png)

**Comment by way2muchnoise** [comment]
Thx for letting me know, something went wrong after Digital Ocean (where I host the service) had some maintenance. Back up and running now :)
