### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by florian-berger** [way2muchnoise/CurseForgeBadge#45]
The certificate of your website expired today. So the badges are no longer displayed and the page is no longer accessible in a secure way.

![image](https://user-images.githubusercontent.com/10084586/202224363-bc14c6f5-d518-4c2b-b7a8-980b5489985d.png)

Please re-new the Let's Encrypt certificate.

**Comment by way2muchnoise** [comment]
Renewed the cert
