### ISSUE TITLE
Addons Badges

### ISSUE THREAD

**Issue by xMrVizzy** [way2muchnoise/CurseForgeBadge#5]
Version Badges doesn't work with Addons: https://minecraft.curseforge.com/projects/faithfulpe-0-16

![screenshot_1](https://cloud.githubusercontent.com/assets/7906418/20925240/91c1c390-bbd7-11e6-8108-c99de52e8aa8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7906418/20925252/a8e5f564-bbd7-11e6-9a5d-321fee07fd04.png)

**Comment by way2muchnoise** [comment]
Looking at it, curse doesn't have the quick overview for addons. like it does for mods

![](http://puu.sh/sGc5X/1b5d4d3fd7.png)![](http://puu.sh/sGc7M/a137e12a88.png)

**Comment by xMrVizzy** [comment]
Okay, i will aks it to Curse Stuff

**Comment by way2muchnoise** [comment]
I guess that would solve the issue, cause it makes it a lot harder (and mainly slower) if I have to go crawl all files available for versions etc. Will leave this open for follow up tho.

**Comment by xMrVizzy** [comment]
Today site is down.

**Comment by way2muchnoise** [comment]
Back up now @xMrVizzy

**Comment by xMrVizzy** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/7906418/21072490/ecffac10-bee6-11e6-9c74-8a4cfa02dbda.png)

**Comment by way2muchnoise** [comment]
Hmm, it is up again now but I wonder why it went down in the first place.
